module.exports = {
    characters: [
        { label: 'Alisa', value: 'alisa' },
        { label: 'Anna', value: 'anna' },
        { label: 'Armor King', value: 'armor_king' },
        { label: 'Asuka', value: 'asuka' },
        { label: 'Azucena', value: 'azucena' },
        { label: 'Bob', value: 'bob' },
        { label: 'Bryan', value: 'bryan' },
        { label: 'Claudio', value: 'claudio' },
        { label: 'Clive', value: 'clive' },
        { label: 'Devil Jin', value: 'devil jin' },
        { label: 'Dragunov', value: 'dragunov' },
        { label: 'Eddy', value: 'eddy' },
        { label: 'Fahkumram', value: 'fahkumram' },
        { label: 'Feng', value: 'feng' },
        { label: 'Heihachi', value: 'heihachi' },
        { label: 'Hwoarang', value: 'hwoarang' },
        { label: 'Jack-8', value: 'jack-8' },
        { label: 'Jin', value: 'jin' },
        { label: 'Jun', value: 'jun' },
        { label: 'Kazuya', value: 'kazuya' },
        { label: 'King', value: 'king' },
        { label: 'Kunimitsu', value: 'kunimitsu' },
        { label: 'Kuma', value: 'kuma' },
        { label: 'Lars', value: 'lars' },
        { label: 'Law', value: 'law' },
        { label: 'Lee', value: 'lee' },
        { label: 'Leo', value: 'leo' },
        { label: 'Leroy', value: 'leroy' },
        { label: 'Lidia', value: 'lidia' },
        { label: 'Lili', value: 'lili' },
        { label: 'Miary Zo', value: 'miary_zo'},
        { label: 'Nina', value: 'nina' },
        { label: 'Panda', value: 'panda' },
        { label: 'Paul', value: 'paul' },
        { label: 'Raven', value: 'raven' },
        { label: 'Reina', value: 'reina' },
        { label: 'Shaheen', value: 'shaheen' },
        { label: 'Steve', value: 'steve' },
        { label: 'Victor', value: 'victor' },
        { label: 'Xiaoyu', value: 'xiaoyu' },
        { label: 'Yoshimitsu', value: 'yoshimitsu' },
        { label: 'Zafina', value: 'zafina' }
    ],
    stages: [
        { label: 'Arena', value: 'arena' },
        { label: 'Arena (Underground)', value: 'arena_underground' },
        { label: 'Baobab Horizon', value: 'baobab_horizon' },
        { label: 'Celebration on the Seine', value: 'celebration_on_the_seine' },
        { label: 'Coliseum of Fate', value: 'coliseum_of_fate' },
        { label: 'Descent into Subconscious', value: 'descent_into_subconscious' },
        { label: 'Elegant Palace', value: 'elegant_palace' },
        { label: 'Fallen Destiny', value: 'fallen_destiny' },
        { label: 'Genmaji Temple', value: 'genmaji_temple' },
        { label: 'Genmaji Temple (Daytime)', value: 'genmaji_temple_daytime' },
        { label: 'Into the Stratosphere', value: 'into_the_stratosphere' },
        { label: 'Midnight Siege', value: 'midnight_siege' },
        { label: 'Ortiz Farm', value: 'ortiz_farm' },
        { label: 'Pac-Pixels', value: 'pac-pixels' },
        { label: 'Phoenix Gate', value: 'phoenix_gate' },
        { label: 'Urban Square', value: 'urban_square' },
        { label: 'Rebel Hangar', value: 'rebel_hangar' },
        { label: 'Sanctum', value: 'sanctum' },
        { label: 'Seaside Resort', value: 'seaside_resort' },
        { label: 'Secluded Training Ground', value: 'secluded_training_ground' },
        { label: 'Urban Square (Evening)', value: 'urban_square_evening' },
        { label: 'Yakushima', value: 'yakushima' }
    ]
};